import 'package:flutter/material.dart';
import 'package:favorite_button/favorite_button.dart';
import 'package:news_app/models/article.dart';
import 'package:news_app/data/tec_service.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:news_app/categories/favoriler.dart';
import 'package:news_app/main.dart';


class  technology extends StatelessWidget {
  const technology({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Teknoloji'),
        centerTitle: true,
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.mobile_friendly),
            disabledColor: Colors.blue,
            onPressed: () {
            },
          ),
        ],
      ),
    );
  }
}


class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  List<Articles> articles = [];

  @override
  void initState() {
    TecService.getAutogenerated().then((value) {
      setState(() {
        articles = value!;
      });
    });
    super.initState();
  }
  int _clickIndex = 0;
  String _selectedMenu = ' ';

  static const optionStyle =
  TextStyle(fontWeight: FontWeight.bold);
  static const List<Widget> _widgetOptions = <Widget>[
    Text(
      'Index 0: HomePage',
      style: optionStyle,
    ),
    Text(
      'Index 1: Search',
      style: optionStyle,
    ),
    Text(
      'Index 2: Settings',
      style: optionStyle,
    ),
  ];
  Color bgColor = Colors.pink;

  dynamic child;

  void _onItemTapped(int index) {
    setState(() {
      _clickIndex = index;
    });
    if (index == 0) {
      bgColor = Colors.purpleAccent;
      setState(() {
        Navigator.push(context, MaterialPageRoute(
            builder: (context) => technology()));
      });
    } else if (index == 1) {
      setState(() {
        bgColor = Colors.deepPurpleAccent;
      });
    } else if (index == 2) {
      setState(() {
        bgColor = Colors.lightGreen;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
        backgroundColor: Colors.pink,
          title: const Text('Teknoloji'),
        centerTitle: true,
    ),
      body: Center(
        child: ListView.builder(
            itemCount: articles.length,
            itemBuilder: (context, index) {
              return Card(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    FavoriteButton(
                      isFavorite: false,
                      valueChanged: (_isFavorite) {
                        print('Is favorite: $_isFavorite');
                        print('fdghjgm');

                      },
                    ),
                    Image.network(articles[index].urlToImage.toString()),

                    ListTile(
                      leading: Icon(Icons.arrow_circle_down),
                      minLeadingWidth: 3,
                      title: Text(articles[index].title.toString(),
                        style: TextStyle(
                            fontSize: 20, fontWeight: FontWeight.bold),),
                      subtitle: Text(articles[index].author.toString()),
                    ),
                    Padding(
                      padding: const EdgeInsets.all(16.0),
                      child: Text(articles[index].description.toString(),
                        style: TextStyle(fontSize: 18),),
                    ),
                    ButtonBar(
                      alignment: MainAxisAlignment.start,
                      children: [
                        FlatButton(
                          color: Colors.white30,
                          textColor: Colors.deepPurple,
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(5)),
                          onPressed: () async {
                            await launch(articles[index].url.toString());
                          },
                          child: Text(
                            'Habere Git',
                            style: TextStyle(fontSize: 18),
                          ),
                        ),
                        StarButton(
                          isStarred: true,
                          iconSize: 50,
                          iconColor: Colors.yellowAccent,
                          iconDisabledColor: Colors.deepOrangeAccent,
                          valueChanged: (_isStarred) {
                            print('Is Starred : $_isStarred');
                          },
                        ),
                      ],
                    ),
                  ],
                ),
              );
            }),
      ),

      bottomNavigationBar: BottomNavigationBar(
        backgroundColor: bgColor,
        selectedItemColor: Colors.white,
        unselectedItemColor: const Color.fromARGB(130, 255, 255, 255),
        selectedFontSize: 20,
        unselectedFontSize: 16,
        showSelectedLabels: true,
        showUnselectedLabels: true,
        items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: 'HomePage',
            backgroundColor: bgColor,
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.search),
            label: 'Search',
            backgroundColor: bgColor,
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
            backgroundColor: bgColor,
          ),
        ],
        currentIndex: _clickIndex,
        onTap: _onItemTapped,
      ),
    );
  }
}


class  FavPage extends StatelessWidget {
  const FavPage ({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Favorite Icon '),
      ),
      body: SizedBox(
        width: MediaQuery.of(context).size.width,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            FavoriteButton(
              isFavorite: false,
              iconColor: Colors.pink,
              iconDisabledColor: Colors.pink,
              valueChanged: (_isFavorite) {
                print('Is Favorite : $_isFavorite');
              },
            ),
            Container(
              decoration: BoxDecoration(
                color: const Color(0xff7c94b6),
                image: const DecorationImage(
                  image: NetworkImage('https://i.gifer.com/6MX.gif'),
                  fit: BoxFit.cover,
                ),
                border: Border.all(
                  width: 8,
                ),
                borderRadius: BorderRadius.circular(12),
              ),
            )
          ],
        ),
      ),
    );
  }
}
